### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by grzhan** [kcwikizh/kcwiki-api#3]
- [ ] **本地json数据迁移到mongodb**
- [ ] 补完舰娘类型`ships/type`，添加英语图鉴名
- [ ] 补完装备类型`slotitems/type`，完成`api_mst_slotitem.api_type`中的其他三个类型（[大分类,图鉴表示,图标ID]）
- [ ] 将初始装备接口`init/equip`与`ship`接口整合
- [x] start2数据不同版本的Diff，在上传接口防止上传相同的start2数据
- [x] 将大鸡丁的start2归档数据整合
- [ ] 尚未整合入start2的数据：`api_msg_const`、`api_mst_equip_exslot`、`api_mst_shipupgrade`
- [x] 给`/servers`的服务器标上ID  http://203.104.209.7/gadget/js/kcs_const.js
- [ ] 整合 kcdata 的任务部分数据
- [ ] 整合 db.kcwiki.moe 的地图标点部分数据作为base
- [x] 部分缓存刷新（/purge）
- [ ] 整合`kcwiki-report`的数据（深海属性、初始装备等）
- [ ] start2接口地图部分发生了更新（`api_mst_mapcell`）貌似被移除，需要跟进更新
